version: '3'

services:
  web:
    build: ./bank_app
    env_file: .env
    environment:
      DEBUG: 'False'
      DATABASE_URL: postgresql://bank_db:pass_db@db:5432/bank_db
    volumes:
      - web-static:/home/app/web/staticfiles
    depends_on:
      - db

  db:
    restart: always
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: bank_db
      POSTGRES_PASSWORD: pass_db
      POSTGRES_DB: bank_db
    volumes:
      - pgdata:/var/lib/postgresql/data/

  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/ssl/private/
      - web-static:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  web-static:
  pgdata: