# Generated by Django 4.2 on 2023-04-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertoconfirm',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
