# Generated by Django 4.2 on 2023-04-30 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='phone',
            field=models.CharField(help_text='Contact phone number', max_length=12, validators=[django.core.validators.RegexValidator('^(\\+48)?\\d{9}$', message='Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
